### ISSUE TITLE
Compute Instance authentication to workspace creation

### ISSUE THREAD

**Issue by lostmygithubaccount** [danielsc/azureml-workshop-2019#59]
Every time you create a new compute instance, then call:

```python
ws = Workspace.from_config()
```

you need to authenticate through the browser by copy/pasting a string:

![image](https://user-images.githubusercontent.com/54814569/72297316-89f2f880-3610-11ea-862d-ba48204a087e.png)

I would expect to not have to do this given I'm using a compute instance in the workspace. 

Also I get the annoying warning pictured above every time I have to do this.

**Comment by CESARDELATORRE** [comment]
File papercut here:

https://msdata.visualstudio.com/Vienna/_workitems/edit/587874
